# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 0 25 12 *"
  workflow_dispatch:

jobs:
  update-age:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Replace age variable
        run: |
          age="$(date -d @$( expr $(expr `date +%s` - `date -d 12/25/2003 +%s`) + `date -d 01/01/2000 +%s`) +%y)"
          sed -i "s/{{ *age *}}/$age/" "$GITHUB_WORKSPACE/README.md.tpl"
          cat "$GITHUB_WORKSPACE/README.md.tpl"
          
      - name: Replace next year variable
        run: |
          year=`expr $(date +%Y) + 1`
          sed -i "s/{{ *nextYear *}}/$year/" "$GITHUB_WORKSPACE/README.md.tpl"
          cat "$GITHUB_WORKSPACE/README.md.tpl"
          
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
